In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4]

In [3]:
my_list

[1, 2, 3, 4]

In [4]:
type(my_list)

list

In [5]:
np.array(my_list)

array([1, 2, 3, 4])

In [6]:
arr = np.array(my_list)

In [7]:
type(arr)

numpy.ndarray

In [8]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [14]:
np.linspace(2,8,10)

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])

In [15]:
np.random.randint(0,10,(3,2))

array([[8, 8],
       [4, 7],
       [6, 7]])

In [16]:
np.random.randint(0,10,(3,2))

array([[9, 2],
       [2, 8],
       [6, 6]])

In [17]:
np.random.seed(99)

np.random.random((3,4))

array([[0.67227856, 0.4880784 , 0.82549517, 0.03144639],
       [0.80804996, 0.56561742, 0.2976225 , 0.04669572],
       [0.9906274 , 0.00682573, 0.76979303, 0.7467671 ]])

In [18]:
np.random.random((3,4))

array([[0.37743894, 0.49414745, 0.92894839, 0.39545404],
       [0.9739563 , 0.52441472, 0.09361309, 0.81330841],
       [0.21168679, 0.55434578, 0.29226912, 0.81614236]])

In [19]:
np.random.seed(99)

np.random.random((3,4))

array([[0.67227856, 0.4880784 , 0.82549517, 0.03144639],
       [0.80804996, 0.56561742, 0.2976225 , 0.04669572],
       [0.9906274 , 0.00682573, 0.76979303, 0.7467671 ]])

In [20]:
arr = np.random.randint(0,100,(3,4))

In [21]:
arr

array([[ 2, 64, 12, 40],
       [72, 20, 59, 39],
       [79, 47, 27, 62]])

In [29]:
arr.max(keepdims=True)

array([[79]])

In [38]:
arr.argmax()

8

In [42]:
arr.argmin(axis=0)

array([0, 1, 0, 1], dtype=int64)

In [43]:
mat = np.arange(1,101).reshape(10,10)

In [44]:
mat

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [45]:
mat[2,2]

23

In [46]:
mat[0:3,0:3]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [47]:
mat[mat > 80]

array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100])

In [48]:
my_filter = mat >50
mat[my_filter]

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])